apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap-appsettings-{{ .Values.cluster }}
  namespace: pathfinder
  labels:
    app: {{ .Chart.Name }}-{{ .Values.cluster }}
    release: {{ .Chart.Name }}-{{ .Values.cluster }}
data:
  appsettings.json: |
{{- if .Values.deployment.appsettings }}
  {{- .Values.deployment.appsettings | toPrettyJson | nindent 4 }} 
{{- end }}  