apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.cluster }}
  namespace: pathfinder
  labels:
    app: {{ .Chart.Name }}-{{ .Values.cluster }}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: {{ .Chart.Name }}-{{ .Values.cluster }}